<?php
namespace C4\Core;

use Symfony\Component\Routing;
use Symfony\Component\HttpKernel;
use Symfony\Component\EventDispatcher\EventDispatcher;
use Symfony\Component\Yaml\Dumper;
use Symfony\Component\Yaml\Parser;
use Symfony\Component\Yaml\Exception\ParseException;
use Monolog\Handler\StreamHandler;
use Monolog\Handler\FirePHPHandler;
use Doctrine\ORM\Tools\Setup;
use Doctrine\ORM\EntityManager;
use Doctrine\Common\ClassLoader;
use Doctrine\Common\Annotations\AnnotationReader;
use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\MongoDB\Connection;
use Doctrine\ODM\MongoDB\Configuration;
use Doctrine\ODM\MongoDB\Mapping\Driver\AnnotationDriver;

require_once 'Doctrine/Common/ClassLoader.php';

class Framework extends HttpKernel\HttpKernel
{
    public static $mainConfiguration;
    public $yamlParser;
    private $logger;
    public $entityManager;
    public $documentManager;

    public function __construct($routes, $logger)
    {
        $this->logger = $logger;
        $this->logger->pushHandler(new StreamHandler(__DIR__.'/../../../logging/System_Log.log', \Monolog\Logger::DEBUG));
        $this->logger->pushHandler(new FirePHPHandler());
        $this->logger->addInfo('My logger is now ready');

        $context = new Routing\RequestContext();
        $matcher = new Routing\Matcher\UrlMatcher($routes, $context);
        $resolver = new HttpKernel\Controller\ControllerResolver();

        $dispatcher = new EventDispatcher();
        $dispatcher->addSubscriber(new HttpKernel\EventListener\RouterListener($matcher));
        $dispatcher->addSubscriber(new HttpKernel\EventListener\ResponseListener('UTF-8'));

        $dispatcher->addSubscriber(new ExceptionListener(function (Request $request)
        {
            $msg = 'Something went wrong! ('.$request->get('exception')->getMessage().')';
            return new Response($msg, 500);
        }
        ));

        // get the main configuration
        $this->parseMainConfiguration();

        // get ORM
        $this->getORM();
        // set up the templating system

        // Profit!!!1

        parent::__construct($dispatcher, $resolver);
    }

    public function parseMainConfiguration()
    {
        try {
            // The YAML parser object can be re-used, so we instantiate it here
            $this->yamlParser = new Parser();
            self::$mainConfiguration = $this->yamlParser->parse(file_get_contents(__DIR__.'/../../../config/systemConfig.yml'));
        } catch (ParseException $e) {
            printf("Unable to parse the YAML string: %s", $e->getMessage());
            die();
        }
        return $this;
    }

    public function parseGeneralConfiguration($configFile)
    {
        try {
            $configuration = $this->yamlParser->parse(
                file_get_contents(__DIR__.'/../../../config/'.$configFile.'.yml')
            );
            return $configuration;
        } catch (ParseException $e) {
            printf("Unable to parse the YAML string: %s", $e->getMessage());
        }
    }

    public function yamlWriter(array $data, $filename)
    {
        $dumper = new Dumper();
        $yaml = $dumper->dump($data);
        file_put_contents(__DIR__.'/../../../config/'.$filename.'.yml', $yaml);
    }

    public static function getConfiguration()
    {
        return self::$mainConfiguration;
    }

    /**
     * Set PHP configuration settings
     *
     * @param  array $settings
     * @return Framework
     */
    public function setPhpSettings(array $settings)
    {
        foreach ($settings as $key => $value) {
            if (is_scalar($value)) {
                ini_set($key, $value);
            }
        }

        return $this;
    }

    /**
     * Set include path
     *
     * @param  array $paths
     * @return Framework
     */
    public function setIncludePaths(array $paths)
    {
        $path = implode(PATH_SEPARATOR, $paths);
        set_include_path($path . PATH_SEPARATOR . get_include_path());
        return $this;
    }

    public function getSession()
    {

    }

    public function setSession()
    {

    }

    /**
     * Method to return an application URI. All URIs pointing at the application
     * must be generated by this method. It is recommended that an action parameter
     * is used to indicate the action being performed.
     * The $mode parameter allows the use of a push/pop mechanism for storing
     * user context for return later. **This needs more work, both implementation
     * and documentation **
     *
     * @access  public
     * @param   array  $params         Associative array of parameter values
     * @param   string $module         Name of module to point to (blank for core actions)
     * @param   string $mode           The URI mode to use, must be one of 'push', 'pop', or 'preserve'
     * @param   string $omitServerName flag to produce relative URLs
     * @param   bool   $javascriptCompatibility flag to produce javascript compatible URLs
     * @returns string $uri the URL
     */
    public function uri(array $params = array(), $module = '', $mode = '', $omitServerName = FALSE, $javascriptCompatibility = FALSE, $Strict = FALSE, $https = FALSE) {
        if (! empty ( $action )) {
            $params ['action'] = $action;
        }
        if ($omitServerName) {
            $uri = $_SERVER ['PHP_SELF'];
        } elseif($https == FALSE) {
            $uri = "http://" . $_SERVER ['HTTP_HOST'] . $_SERVER ['PHP_SELF'];
        }
        else {
            $uri = "https://" . $_SERVER ['HTTP_HOST'] . $_SERVER ['PHP_SELF'];
        }
        if ($mode == 'push' && $this->getParam ( '_pushed_action' )) {
            $mode = 'preserve';
        }
        if ($mode == 'pop') {
            $params ['module'] = $this->getParam ( '_pushed_module', '' );
            $params ['action'] = $this->getParam ( '_pushed_action', '' );
        }
        if (in_array ( $mode, array ('push', 'pop', 'preserve' ) )) {
            $excluded = array ('action', 'module' );
            if ($mode == 'pop') {
                $excluded [] = '_pushed_action';
                $excluded [] = '_pushed_module';
            }
            foreach ( $_GET as $key => $value ) {
                //echo "using GET";
                if (! isset ( $params [$key] ) && ! in_array ( $key, $excluded )) {
                    $params [$key] = $value;
                }
            }
            if ($mode == 'push') {
                $params ['_pushed_module'] = $this->_moduleName;
                $params ['_pushed_action'] = $this->_action;
            }
        } elseif ($mode != '') {
            throw new Exception ( "Incorrect URI mode in Framework::uri" );
        }
        if (count ( $params ) > 1) {
            $params = array_reverse ( $params, TRUE );
        }
        $params ['module'] = $module;
        $params = array_reverse ( $params, TRUE );
        if (! empty ( $params )) {
            $output = array ();

            foreach ( $params as $key => $item ) {
                if (! is_null ( $item )) {
                    $output [] = urlencode ( $key ) . "=" . urlencode ( $item );
                }
            }
            $uri .= '?' . implode ( $javascriptCompatibility ? ($Strict ? '&' : '&#38;') : '&amp;', $output );
        }
        return $uri;
    }

    private function getMongoODM()
    {
        // ODM Classes
        $classLoader = new ClassLoader('Doctrine\ODM\MongoDB', 'lib/vendor/doctrine-mongodb-odm/lib');
        $classLoader->register();

        // Common Classes
        $classLoader = new ClassLoader('Doctrine\Common',
                                       'lib/vendor/doctrine-mongodb-odm/lib/vendor/doctrine-common/lib');
        $classLoader->register();

        // MongoDB Classes
        $classLoader = new ClassLoader('Doctrine\MongoDB',
                                       'lib/vendor/doctrine-mongodb-odm/lib/vendor/doctrine-mongodb/lib');
        $classLoader->register();

        // Document classes
        $classLoader = new ClassLoader('Documents', __DIR__);
        $classLoader->register();

        $config = new Configuration();
        $config->setProxyDir(__DIR__ . '/cache');
        $config->setProxyNamespace('Proxies');

        $config->setHydratorDir(__DIR__ . '/cache');
        $config->setHydratorNamespace('Hydrators');

        $reader = new AnnotationReader();
        $reader->setDefaultAnnotationNamespace('Doctrine\ODM\MongoDB\Mapping\\');
        $config->setMetadataDriverImpl(new AnnotationDriver($reader, __DIR__ . '/Documents'));

        $this->documentManager = DocumentManager::create(new Connection(), $config);
        return $this;
    }

    private function getORM()
    {
        // set up the database connection
        $loader = new \Doctrine\Common\ClassLoader("Doctrine");
        $loader->register();

        $dbParams = array(
                    'driver' => 'pdo_mysql',
                    'user' => 'root',
                    'password' => '',
                    'dbname' => 'c4'
        );
        $path = array(__DIR__ . '/entities');
        $config = Setup::createAnnotationMetadataConfiguration($path, true);
        $this->entityManager = EntityManager::create($dbParams, $config);

        return $this;
    }
}